openapi: 3.0.0
info:
  version: 1.0.0
  title: Guest Order API
components:
  securitySchemes:
    ShopperToken:
      type: http
      scheme: bearer
      flows:
        authorizationCode:
          authorizationUrl: https://shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/authorize
          tokenUrl: https://shortcode.api.commercecloud.salesforce.com/shopper/auth/v1/organizations/my-org-id/oauth2/token
          scopes:
            c_guestOrder_rw: Read order information
paths:
  /{orderNo}:
    get:
      summary: "Gets a guest order by order number and 2 other factors."
      operationId: getGuestOrder
      parameters:
        - in: path
          name: orderNo
          required: true
          schema:
            type: string
        - in: query
          name: c_email
          required: true
          schema:
            type: string
        - in: query
          name: c_postalCode
          required: true
          schema:
            type: string
        - in: query
          name: c_subAPI
          required: false
          schema:
            type: string
        - in: query
          name: c_lines
          required: false
          schema:
            type: string            
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        200:
          description: OK
security:
  - ShopperToken: ["c_guestOrder_rw"]
