openapi: 3.0.0
info:
  version: 1.0.0
  title: My Admin API
components:
  securitySchemes:
    AmOAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://account.demandware.com/dwsso/oauth2/authorize
          tokenUrl: https://account.demandware.com/dwsso/oauth2/access_token
          scopes:
            c_myadmin: Read  information
        clientCredentials:
          tokenUrl: https://account.demandware.com/dwsso/oauth2/access_token
          scopes:
            c_myadmin: Read  information
paths:
  /something:
    get:
      summary: "Get something"
      operationId: getSomething
      parameters:
        - in: query
          name: siteId
          required: false
          schema:
            type: string
            minLength: 1
      responses:
        200:
          description: OK
security:
  - AmOAuth2: ["c_myadmin"]
